### ISSUE TITLE
怎么才能联系到作者您？

### ISSUE THREAD

**Issue by VliceZ** [zerochl/WalletConnect#3]
WalletConnect的的文档极其不友好，demo又只有iOS端的。我们的需要接入实在是不知道从哪里下手，希望能加下微信或Q求助一下，感谢。

**Comment by zerochl** [comment]
有问题直接github问吧。
或者区块链的方式：（EOS）galaxynibiru，通过转账0.0001 EOS发送消息给我。

**Comment by VliceZ** [comment]
我们有一个需求，是通过WalletConnect导入其他钱包里面的钱包（比如，TpToken,imToken,My Key），获取用户在其他钱包已经导入的钱包地址。因为walletconnect几乎没有文档，且demo又跑不起来，这个需求不知道如何下手，所以想详细请教一下。

**Comment by zerochl** [comment]
没明白你什么意思，walletconnect是H5与钱包关系的建立，walletconnect是不可能会给你其他钱包的账户信息的，如果你是钱包，那么你需要扫码或者通过深度链接拿到H5的信息，发送给walletconnect服务端之后，服务端会发送建立链接的请求给你，授权你的钱包地址给walletconnect对接的H5.

**Comment by VliceZ** [comment]
谢谢你的解答，问题已经解决了
